In [1]:
import pandas as pd
import re

In [2]:
#loading a transaction dataset
transaction_data = pd.read_excel("QVI_transaction_data.xlsx")
transaction_data

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8
...,...,...,...,...,...,...,...,...
264831,43533,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream 175g,2,10.8
264832,43325,272,272358,270154,74,Tostitos Splash Of Lime 175g,1,4.4
264833,43410,272,272379,270187,51,Doritos Mexicana 170g,2,8.8
264834,43461,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno 150g,2,7.8
264835,43365,272,272380,270189,74,Tostitos Splash Of Lime 175g,2,8.8

In [3]:
#performing EDA on transaction dataset
transaction_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATE            264836 non-null  int64
 1   STORE_NBR       264836 non-null  int64
 2   LYLTY_CARD_NBR  264836 non-null  int64
 3   TXN_ID          264836 non-null  int64
 4   PROD_NBR        264836 non-null  int64
 5   PROD_NAME       264836 non-null  object
 6   PROD_QTY        264836 non-null  int64
 7   TOT_SALES       264836 non-null  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 16.2+ MB

In [4]:
transaction_data.describe()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_QTY,TOT_SALES
count,264836.000000,264836.00000,2.648360e+05,2.648360e+05,264836.000000,264836.000000,264836.000000
mean,43464.036260,135.08011,1.355495e+05,1.351583e+05,56.583157,1.907309,7.304200
std,105.389282,76.78418,8.057998e+04,7.813303e+04,32.826638,0.643654,3.083226
min,43282.000000,1.00000,1.000000e+03,1.000000e+00,1.000000,1.000000,1.500000
25%,43373.000000,70.00000,7.002100e+04,6.760150e+04,28.000000,2.000000,5.400000
50%,43464.000000,130.00000,1.303575e+05,1.351375e+05,56.000000,2.000000,7.400000
75%,43555.000000,203.00000,2.030942e+05,2.027012e+05,85.000000,2.000000,9.200000
max,43646.000000,272.00000,2.373711e+06,2.415841e+06,114.000000,200.000000,650.000000

In [5]:
transaction_data.isnull().sum()

DATE              0
STORE_NBR         0
LYLTY_CARD_NBR    0
TXN_ID            0
PROD_NBR          0
PROD_NAME         0
PROD_QTY          0
TOT_SALES         0
dtype: int64

In [6]:
transaction_data.count()

DATE              264836
STORE_NBR         264836
LYLTY_CARD_NBR    264836
TXN_ID            264836
PROD_NBR          264836
PROD_NAME         264836
PROD_QTY          264836
TOT_SALES         264836
dtype: int64

In [7]:
#Loading purchase behaviour dataset
purchase_behaviour_data = pd.read_csv("QVI_purchase_behaviour.csv")
purchase_behaviour_data

       LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0                1000   YOUNG SINGLES/COUPLES          Premium
1                1002   YOUNG SINGLES/COUPLES       Mainstream
2                1003          YOUNG FAMILIES           Budget
3                1004   OLDER SINGLES/COUPLES       Mainstream
4                1005  MIDAGE SINGLES/COUPLES       Mainstream
...               ...                     ...              ...
72632         2370651  MIDAGE SINGLES/COUPLES       Mainstream
72633         2370701          YOUNG FAMILIES       Mainstream
72634         2370751          YOUNG FAMILIES          Premium
72635         2370961          OLDER FAMILIES           Budget
72636         2373711   YOUNG SINGLES/COUPLES       Mainstream

[72637 rows x 3 columns]

In [8]:
#performing EDA on purchase behaviour dataset
purchase_behaviour_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72637 entries, 0 to 72636
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LYLTY_CARD_NBR    72637 non-null  int64
 1   LIFESTAGE         72637 non-null  object
 2   PREMIUM_CUSTOMER  72637 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.7+ MB

In [9]:
purchase_behaviour_data.describe()

       LYLTY_CARD_NBR
count    7.263700e+04
mean     1.361859e+05
std      8.989293e+04
min      1.000000e+03
25%      6.620200e+04
50%      1.340400e+05
75%      2.033750e+05
max      2.373711e+06

In [10]:
purchase_behaviour_data.count()

LYLTY_CARD_NBR      72637
LIFESTAGE           72637
PREMIUM_CUSTOMER    72637
dtype: int64

In [11]:
transaction_data.shape

(264836, 8)

In [12]:
purchase_behaviour_data.shape

(72637, 3)

In [13]:
transaction_data.columns

Index(['DATE', 'STORE_NBR', 'LYLTY_CARD_NBR', 'TXN_ID', 'PROD_NBR',
       'PROD_NAME', 'PROD_QTY', 'TOT_SALES'],
      dtype='object')

In [14]:
purchase_behaviour_data.columns

Index(['LYLTY_CARD_NBR', 'LIFESTAGE', 'PREMIUM_CUSTOMER'], dtype='object')

In [15]:
transaction_data.duplicated().sum()
#one rows is identited as duplicated

np.int64(1)

In [16]:
#verifying duplicate values
duplicate_rows = transaction_data[transaction_data.duplicated(keep=False)]
duplicate_rows

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
124843,43374,107,107024,108462,45,Smiths Thinly Cut Roast Chicken 175g,2,6.0
124845,43374,107,107024,108462,45,Smiths Thinly Cut Roast Chicken 175g,2,6.0

In [17]:
#droping or deleting the duplicate values
transaction_data = transaction_data.drop_duplicates()

In [18]:
#One duplicate transaction value was identited and deleted to maintain data integrity

In [19]:
purchase_behaviour_data.duplicated().sum()
#zero rows are identited as duplicated

np.int64(0)

In [20]:
transaction_data.describe()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_QTY,TOT_SALES
count,264835.000000,264835.000000,2.648350e+05,2.648350e+05,264835.000000,264835.000000,264835.000000
mean,43464.036600,135.080216,1.355496e+05,1.351584e+05,56.583201,1.907308,7.304205
std,105.389336,76.784306,8.058011e+04,7.813316e+04,32.826692,0.643655,3.083231
min,43282.000000,1.000000,1.000000e+03,1.000000e+00,1.000000,1.000000,1.500000
25%,43373.000000,70.000000,7.002100e+04,6.760100e+04,28.000000,2.000000,5.400000
50%,43464.000000,130.000000,1.303580e+05,1.351380e+05,56.000000,2.000000,7.400000
75%,43555.000000,203.000000,2.030945e+05,2.027015e+05,85.000000,2.000000,9.200000
max,43646.000000,272.000000,2.373711e+06,2.415841e+06,114.000000,200.000000,650.000000

In [21]:
transaction_data["PROD_QTY"].value_counts().sort_index()

PROD_QTY
1       27518
2      236038
3         430
4         397
5         450
200         2
Name: count, dtype: int64

In [22]:
#identifying outliers in transaction dataset
transaction_data[transaction_data["PROD_QTY"]>5]

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
69762,43331,226,226000,226201,4,Dorito Corn Chp Supreme 380g,200,650.0
69763,43605,226,226000,226210,4,Dorito Corn Chp Supreme 380g,200,650.0

In [23]:
#Confirming that identifed outlier is real
print(transaction_data[transaction_data['LYLTY_CARD_NBR']==226000])
print()
print(purchase_behaviour_data[purchase_behaviour_data['LYLTY_CARD_NBR']==226000])

        DATE  STORE_NBR  LYLTY_CARD_NBR  TXN_ID  PROD_NBR  \
69762  43331        226          226000  226201         4
69763  43605        226          226000  226210         4

                              PROD_NAME  PROD_QTY  TOT_SALES
69762  Dorito Corn Chp     Supreme 380g       200      650.0
69763  Dorito Corn Chp     Supreme 380g       200      650.0

       LYLTY_CARD_NBR       LIFESTAGE PREMIUM_CUSTOMER
59694          226000  OLDER FAMILIES          Premium

In [24]:
#removing the outlier from transaction dataset
transaction_data = transaction_data[transaction_data['LYLTY_CARD_NBR'] != 226000]

In [25]:
#verifying that column is removed from the dataset or not.
transaction_data['LYLTY_CARD_NBR'].describe()

count    2.648330e+05
mean     1.355489e+05
std      8.058003e+04
min      1.000000e+03
25%      7.002100e+04
50%      1.303570e+05
75%      2.030940e+05
max      2.373711e+06
Name: LYLTY_CARD_NBR, dtype: float64

In [26]:
transaction_data

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8
...,...,...,...,...,...,...,...,...
264831,43533,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream 175g,2,10.8
264832,43325,272,272358,270154,74,Tostitos Splash Of Lime 175g,1,4.4
264833,43410,272,272379,270187,51,Doritos Mexicana 170g,2,8.8
264834,43461,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno 150g,2,7.8
264835,43365,272,272380,270189,74,Tostitos Splash Of Lime 175g,2,8.8

In [27]:
transaction_data['DATE'].dtype

dtype('int64')

In [28]:
transaction_data["DATE"] = pd.to_datetime(
    transaction_data["DATE"],
    origin="1899-12-30",
    unit="D"
)

In [29]:
transaction_data.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

In [30]:
#checking for the Maximum and Minimum date time in transaction dataset
print("The maximum date is : ",transaction_data['DATE'].max())
print("The minimum date is : ",transaction_data['DATE'].min())

The maximum date is :  2019-06-30 00:00:00
The minimum date is :  2018-07-01 00:00:00

In [31]:
# extracting Brand Name (first word)
transaction_data["BRAND_NAME"] = transaction_data["PROD_NAME"].str.extract(r'^([A-Za-z0-9&\'\-]+)')
transaction_data

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,BRAND_NAME
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,Natural
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,CCs
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,Smiths
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,Smiths
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,Kettle
...,...,...,...,...,...,...,...,...,...
264831,2019-03-09,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream 175g,2,10.8,Kettle
264832,2018-08-13,272,272358,270154,74,Tostitos Splash Of Lime 175g,1,4.4,Tostitos
264833,2018-11-06,272,272379,270187,51,Doritos Mexicana 170g,2,8.8,Doritos
264834,2018-12-27,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno 150g,2,7.8,Doritos
264835,2018-09-22,272,272380,270189,74,Tostitos Splash Of Lime 175g,2,8.8,Tostitos

In [32]:
# Pack Size
pack_pattern = r'(\d+(?:\.\d+)?\s?(?:kg|g|mg|l|ml|oz|lb|cl|pk|pcs|pc|ct))\b'

transaction_data["PACK_SIZE"] = (
    transaction_data["PROD_NAME"]
      .str.extract(pack_pattern, flags=re.IGNORECASE)[0]
      .str.replace(r"\s+", "", regex=True)
      .str.lower()
)

In [33]:
transaction_data

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,BRAND_NAME,PACK_SIZE
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,Natural,175g
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,CCs,175g
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,Smiths,170g
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,Smiths,175g
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,Kettle,150g
...,...,...,...,...,...,...,...,...,...,...
264831,2019-03-09,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream 175g,2,10.8,Kettle,175g
264832,2018-08-13,272,272358,270154,74,Tostitos Splash Of Lime 175g,1,4.4,Tostitos,175g
264833,2018-11-06,272,272379,270187,51,Doritos Mexicana 170g,2,8.8,Doritos,170g
264834,2018-12-27,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno 150g,2,7.8,Doritos,150g
264835,2018-09-22,272,272380,270189,74,Tostitos Splash Of Lime 175g,2,8.8,Tostitos,175g

In [34]:
transaction_data['BRAND_NAME'].value_counts()

BRAND_NAME
Kettle        41288
Smiths        28859
Pringles      25102
Doritos       24962
Thins         14075
RRD           11894
Infuzions     11057
WW            10320
Cobs           9693
Tostitos       9471
Twisties       9454
Old            9324
Tyrrells       6442
Grain          6272
Natural        6050
Red            5885
Cheezels       4603
CCs            4551
Woolworths     4437
Dorito         3183
Infzns         3144
Smith          2963
Cheetos        2927
Snbts          1576
Burger         1564
GrnWves        1468
Sunbites       1432
NCC            1419
French         1418
Name: count, dtype: int64

In [35]:
sorted(transaction_data['BRAND_NAME'].unique())

['Burger',
 'CCs',
 'Cheetos',
 'Cheezels',
 'Cobs',
 'Dorito',
 'Doritos',
 'French',
 'Grain',
 'GrnWves',
 'Infuzions',
 'Infzns',
 'Kettle',
 'NCC',
 'Natural',
 'Old',
 'Pringles',
 'RRD',
 'Red',
 'Smith',
 'Smiths',
 'Snbts',
 'Sunbites',
 'Thins',
 'Tostitos',
 'Twisties',
 'Tyrrells',
 'WW',
 'Woolworths']

In [36]:
unique_value = transaction_data.loc[transaction_data['BRAND_NAME'] == 'RRD']

In [37]:
unique_value

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,BRAND_NAME,PACK_SIZE
92,2019-05-18,120,120226,123743,67,RRD Chilli& Coconut 150g,1,2.7,RRD,150g
118,2019-05-19,164,164183,164919,67,RRD Chilli& Coconut 150g,1,2.7,RRD,150g
140,2018-08-16,191,191200,192940,53,RRD Sweet Chilli & Sour Cream 165g,1,3.0,RRD,165g
294,2019-01-17,5,5018,4467,53,RRD Sweet Chilli & Sour Cream 165g,2,6.0,RRD,165g
302,2018-08-11,5,5028,4535,67,RRD Chilli& Coconut 150g,2,5.4,RRD,150g
...,...,...,...,...,...,...,...,...,...,...
264752,2018-07-30,268,268365,264802,103,RRD Steak & Chimuchurri 150g,1,2.7,RRD,150g
264761,2019-06-21,269,269125,265778,11,RRD Pc Sea Salt 165g,2,6.0,RRD,165g
264778,2019-06-02,269,269204,266273,67,RRD Chilli& Coconut 150g,2,5.4,RRD,150g
264781,2019-02-08,269,269222,266383,11,RRD Pc Sea Salt 165g,2,6.0,RRD,165g
264814,2018-08-30,271,271193,269364,10,RRD SR Slow Rst Pork Belly 150g,2,5.4,RRD,150g

In [38]:
print(transaction_data[
    transaction_data["BRAND_NAME"]=="Natural"
]["PROD_NAME"].unique())

print(transaction_data[
    transaction_data["BRAND_NAME"]=="Old"
]["PROD_NAME"].unique())

['Natural Chip        Compny SeaSalt175g'
 'Natural ChipCo      Hony Soy Chckn175g'
 'Natural Chip Co     Tmato Hrb&Spce 175g'
 'Natural ChipCo Sea  Salt & Vinegr 175g']
['Old El Paso Salsa   Dip Tomato Mild 300g'
 'Old El Paso Salsa   Dip Chnky Tom Ht300g'
 'Old El Paso Salsa   Dip Tomato Med 300g']

In [39]:
#creating a mapping
brand_mapping = {
    'Infzns' : 'Infuzions',
    'Dorito' : 'Doritos',
    'Smith' : 'Smiths',
    'Grain' : 'GrnWves',
    'Red' : 'RRD',
    'WW' : 'Woolworths',
    'Snbts' : 'Sunbites',
    'Natural' : 'Natural Chip Co',
    'Old' : 'Old El Paso'
}

In [40]:
#standarizing the names
transaction_data["BRAND_NAME"] = transaction_data["BRAND_NAME"].replace(brand_mapping)

In [41]:
transaction_data

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,BRAND_NAME,PACK_SIZE
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,Natural Chip Co,175g
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,CCs,175g
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,Smiths,170g
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,Smiths,175g
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,Kettle,150g
...,...,...,...,...,...,...,...,...,...,...
264831,2019-03-09,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream 175g,2,10.8,Kettle,175g
264832,2018-08-13,272,272358,270154,74,Tostitos Splash Of Lime 175g,1,4.4,Tostitos,175g
264833,2018-11-06,272,272379,270187,51,Doritos Mexicana 170g,2,8.8,Doritos,170g
264834,2018-12-27,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno 150g,2,7.8,Doritos,150g
264835,2018-09-22,272,272380,270189,74,Tostitos Splash Of Lime 175g,2,8.8,Tostitos,175g

In [42]:
transaction_data.to_excel("Final_transaction_data.xlsx",index=False)

In [43]:
#Merging Final transaction datatset with purchase behaviour dataset
merged_data = pd.merge(
    transaction_data,
    purchase_behaviour_data,
    on="LYLTY_CARD_NBR",
    how="left"
)

In [44]:
merged_data.shape

(264833, 12)

In [46]:
merged_data.isnull().sum()

DATE                0
STORE_NBR           0
LYLTY_CARD_NBR      0
TXN_ID              0
PROD_NBR            0
PROD_NAME           0
PROD_QTY            0
TOT_SALES           0
BRAND_NAME          0
PACK_SIZE           0
LIFESTAGE           0
PREMIUM_CUSTOMER    0
dtype: int64

In [47]:
merged_data.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,BRAND_NAME,PACK_SIZE,LIFESTAGE,PREMIUM_CUSTOMER
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,Natural Chip Co,175g,YOUNG SINGLES/COUPLES,Premium
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,CCs,175g,MIDAGE SINGLES/COUPLES,Budget
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,Smiths,170g,MIDAGE SINGLES/COUPLES,Budget
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,Smiths,175g,MIDAGE SINGLES/COUPLES,Budget
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,Kettle,150g,MIDAGE SINGLES/COUPLES,Budget

In [48]:
#adding a metrics (Price Per Unit)
merged_data["PRICE_PER_UNIT"] = (
    merged_data["TOT_SALES"] / merged_data["PROD_QTY"]
)

In [49]:
merged_data

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,BRAND_NAME,PACK_SIZE,LIFESTAGE,PREMIUM_CUSTOMER,PRICE_PER_UNIT
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,Natural Chip Co,175g,YOUNG SINGLES/COUPLES,Premium,3.00
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,CCs,175g,MIDAGE SINGLES/COUPLES,Budget,2.10
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,Smiths,170g,MIDAGE SINGLES/COUPLES,Budget,1.45
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,Smiths,175g,MIDAGE SINGLES/COUPLES,Budget,3.00
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,Kettle,150g,MIDAGE SINGLES/COUPLES,Budget,4.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
264828,2019-03-09,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream 175g,2,10.8,Kettle,175g,YOUNG SINGLES/COUPLES,Premium,5.40
264829,2018-08-13,272,272358,270154,74,Tostitos Splash Of Lime 175g,1,4.4,Tostitos,175g,YOUNG SINGLES/COUPLES,Premium,4.40
264830,2018-11-06,272,272379,270187,51,Doritos Mexicana 170g,2,8.8,Doritos,170g,YOUNG SINGLES/COUPLES,Premium,4.40
264831,2018-12-27,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno 150g,2,7.8,Doritos,150g,YOUNG SINGLES/COUPLES,Premium,3.90
264832,2018-09-22,272,272380,270189,74,Tostitos Splash Of Lime 175g,2,8.8,Tostitos,175g,YOUNG SINGLES/COUPLES,Premium,4.40

In [50]:
#which lifestage has generated more revenue
merged_data.groupby("LIFESTAGE")["TOT_SALES"].sum().sort_values(ascending=False)

LIFESTAGE
OLDER SINGLES/COUPLES     402420.75
RETIREES                  366470.90
OLDER FAMILIES            352467.20
YOUNG FAMILIES            316160.10
YOUNG SINGLES/COUPLES     260405.30
MIDAGE SINGLES/COUPLES    184751.30
NEW FAMILIES               50433.45
Name: TOT_SALES, dtype: float64

In [51]:
#which customer category has generated more sales
merged_data.groupby("PREMIUM_CUSTOMER")["TOT_SALES"].sum()

PREMIUM_CUSTOMER
Budget        676211.55
Mainstream    750744.50
Premium       506152.95
Name: TOT_SALES, dtype: float64

In [52]:
#who has generated more sales in both category
merged_data.groupby(
    ["LIFESTAGE","PREMIUM_CUSTOMER"]
)["TOT_SALES"].sum()

LIFESTAGE               PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES  Budget               35514.80
                        Mainstream           90803.85
                        Premium              58432.65
NEW FAMILIES            Budget               21928.45
                        Mainstream           17013.90
                        Premium              11491.10
OLDER FAMILIES          Budget              168363.25
                        Mainstream          103445.55
                        Premium              80658.40
OLDER SINGLES/COUPLES   Budget              136769.80
                        Mainstream          133393.80
                        Premium             132257.15
RETIREES                Budget              113147.80
                        Mainstream          155677.05
                        Premium              97646.05
YOUNG FAMILIES          Budget              139345.85
                        Mainstream           92788.75
                        Premium              84025.50
YOUNG SINGLES/COUPLES   Budget               61141.60
                        Mainstream          157621.60
                        Premium              41642.10
Name: TOT_SALES, dtype: float64

In [53]:
# unique customers in each segments
merged_data.groupby(
    ["LIFESTAGE","PREMIUM_CUSTOMER"]
)["LYLTY_CARD_NBR"].nunique()

LIFESTAGE               PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES  Budget              1504
                        Mainstream          3340
                        Premium             2431
NEW FAMILIES            Budget              1112
                        Mainstream           849
                        Premium              588
OLDER FAMILIES          Budget              4675
                        Mainstream          2831
                        Premium             2273
OLDER SINGLES/COUPLES   Budget              4929
                        Mainstream          4930
                        Premium             4750
RETIREES                Budget              4454
                        Mainstream          6479
                        Premium             3872
YOUNG FAMILIES          Budget              4017
                        Mainstream          2728
                        Premium             2433
YOUNG SINGLES/COUPLES   Budget              3779
                        Mainstream          8088
                        Premium             2574
Name: LYLTY_CARD_NBR, dtype: int64

In [54]:
#average spend per customers
merged_data.groupby(
    ['LIFESTAGE','PREMIUM_CUSTOMER']
)['TOT_SALES'].mean()

LIFESTAGE               PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES  Budget              7.074661
                        Mainstream          7.647284
                        Premium             7.112056
NEW FAMILIES            Budget              7.297321
                        Mainstream          7.317806
                        Premium             7.231655
OLDER FAMILIES          Budget              7.269570
                        Mainstream          7.262395
                        Premium             7.208079
OLDER SINGLES/COUPLES   Budget              7.430315
                        Mainstream          7.282116
                        Premium             7.449848
RETIREES                Budget              7.443445
                        Mainstream          7.252262
                        Premium             7.456174
YOUNG FAMILIES          Budget              7.287201
                        Mainstream          7.189025
                        Premium             7.266756
YOUNG SINGLES/COUPLES   Budget              6.615624
                        Mainstream          7.558339
                        Premium             6.629852
Name: TOT_SALES, dtype: float64

In [55]:
#Average quantity purchased
merged_data.groupby(
    ['LIFESTAGE','PREMIUM_CUSTOMER']
)['PROD_QTY'].mean()

LIFESTAGE               PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES  Budget              1.891633
                        Mainstream          1.911656
                        Premium             1.889727
NEW FAMILIES            Budget              1.853910
                        Mainstream          1.857634
                        Premium             1.860919
OLDER FAMILIES          Budget              1.945812
                        Mainstream          1.948610
                        Premium             1.945576
OLDER SINGLES/COUPLES   Budget              1.913403
                        Mainstream          1.910525
                        Premium             1.914268
RETIREES                Budget              1.892244
                        Mainstream          1.887543
                        Premium             1.900122
YOUNG FAMILIES          Budget              1.940749
                        Mainstream          1.940342
                        Premium             1.937732
YOUNG SINGLES/COUPLES   Budget              1.803830
                        Mainstream          1.852498
                        Premium             1.804012
Name: PROD_QTY, dtype: float64

In [56]:
#which brand is more popular
merged_data.groupby('BRAND_NAME')['TOT_SALES'].sum().sort_values(ascending=False)

BRAND_NAME
Kettle             390239.8
Doritos            240590.9
Smiths             224654.2
Pringles           177655.5
Infuzions           99047.6
RRD                 95046.0
Old El Paso         90785.1
Thins               88852.5
Twisties            81522.1
Tostitos            79789.6
Cobs                70569.8
Tyrrells            51647.4
GrnWves             51617.2
Woolworths          49343.6
Cheezels            40029.9
Natural Chip Co     34272.0
CCs                 18078.9
Cheetos             16884.5
Sunbites             9676.4
NCC                  8046.0
French               7929.0
Burger               6831.0
Name: TOT_SALES, dtype: float64

In [57]:
#pack size popular
merged_data.groupby('PACK_SIZE')['TOT_SALES'].sum().sort_values(ascending=False)

PACK_SIZE
175g    485431.4
150g    304288.5
134g    177655.5
110g    162765.4
170g    146673.0
330g    136794.3
300g    113330.6
165g    101360.6
380g     75419.6
270g     55425.4
210g     43048.8
250g     26096.7
135g     26090.4
200g     16007.5
190g     14412.9
160g     10647.6
90g       9676.4
180g      8568.4
70g       6852.0
220g      6831.0
125g      5733.0
Name: TOT_SALES, dtype: float64

In [58]:
merged_data.to_excel("Final_merge_dataset_for_Quantium_dataAnalysis.xlsx",index=False)

In [ ]:
#build Graphs like :
#1. Sales Vs Brand
#2. Sales Vs Pack Size
#3. Sales Vs Premium Customer Segment
#4. Sales Vs Life Stage